<?php
namespace admin\models\video;

class VideoUploadTask extends \common\models\video\VideoUploadTask
{

    public $upload_file;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['video_id', 'upload_type', 'status', 'import_chapters', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['file'], 'string', 'max' => 256],
            [['upload_type', ], 'required']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => '文件地址',
            'upload_file' => '文件',
            'video_id' => '影视ID',
            'upload_type' => '上传类型',
            'status' => '状态',
            'import_chapters' => '入库剧集数',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }

    public function getVideo()
    {
        return $this->hasOne(Video::className(), ['id' => 'video_id']);
    }

    public function beforeSave($insert)
    {

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}