<?php

namespace common\models\user;

use common\helpers\RedisKey;
use common\helpers\Tool;
use Yii;

/**
 * This is the model class for table "{{%sign}}".
 *
 * @property int $id
 * @property int $day 天
 * @property int $score 获得积分数
 * @property int $created_at
 * @property int $updated_at
 */
class Sign extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%sign}}';
    }


    public function afterSave($insert, $changedAttributes)
    {
        if (!$insert) {
            // 清理缓存
            Tool::clearCache(RedisKey::getSettingKey('sign'));
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
