<?php

namespace common\helpers;

use Yii;

/**
 * 图标
 */
class Icon
{
    /**
     * SimpleLine图标
     *
     * @return array
     */
    public static function simpleLines()
    {
        return [
          1 => 'icon-action-redo',
          2 => 'icon-action-undo',
          3 => 'icon-anchor',
          4 => 'icon-arrow-down',
          5 => 'icon-arrow-left',
          6 => 'icon-arrow-right',
          7 => 'icon-arrow-up',
          8 => 'icon-badge',
          9 => 'icon-bag',
          10 => 'icon-ban',
          11 => 'icon-bar-chart',
          12 => 'icon-basket',
          13 => 'icon-basket-loaded',
          14 => 'icon-bell',
          15 => 'icon-book-open',
          16 => 'icon-briefcase',
          17 => 'icon-bubble',
          18 => 'icon-bubbles',
          19 => 'icon-bulb',
          20 => 'icon-calculator',
          21 => 'icon-calendar',
          22 => 'icon-call-end',
          23 => 'icon-call-in',
          24 => 'icon-call-out',
          25 => 'icon-camcorder',
          26 => 'icon-camera',
          27 => 'icon-check',
          28 => 'icon-chemistry',
          29 => 'icon-clock',
          30 => 'icon-close',
          31 => 'icon-cloud-download',
          32 => 'icon-cloud-upload',
          33 => 'icon-compass',
          34 => 'icon-control-end',
          35 => 'icon-control-forward',
          36 => 'icon-control-pause',
          37 => 'icon-control-play',
          38 => 'icon-control-rewind',
          39 => 'icon-control-start',
          40 => 'icon-credit-card',
          41 => 'icon-crop',
          42 => 'icon-cup',
          43 => 'icon-cursor',
          44 => 'icon-cursor-move',
          45 => 'icon-diamond',
          46 => 'icon-direction',
          47 => 'icon-directions',
          48 => 'icon-disc',
          49 => 'icon-dislike',
          50 => 'icon-doc',
          51 => 'icon-docs',
          52 => 'icon-drawer',
          53 => 'icon-drop',
          54 => 'icon-earphones',
          55 => 'icon-earphones-alt',
          56 => 'icon-emoticon-smile',
          57 => 'icon-energy',
          58 => 'icon-envelope',
          59 => 'icon-envelope-letter',
          60 => 'icon-envelope-open',
          61 => 'icon-equalizer',
          62 => 'icon-eye',
          63 => 'icon-eyeglasses',
          64 => 'icon-feed',
          65 => 'icon-film',
          66 => 'icon-fire',
          67 => 'icon-flag',
          68 => 'icon-folder',
          69 => 'icon-folder-alt',
          70 => 'icon-frame',
          71 => 'icon-game-controller',
          72 => 'icon-ghost',
          73 => 'icon-globe',
          74 => 'icon-globe-alt',
          75 => 'icon-graduation',
          76 => 'icon-graph',
          77 => 'icon-grid',
          78 => 'icon-handbag',
          79 => 'icon-heart',
          80 => 'icon-home',
          81 => 'icon-hourglass',
          82 => 'icon-info',
          83 => 'icon-key',
          84 => 'icon-layers',
          85 => 'icon-like',
          86 => 'icon-link',
          87 => 'icon-list',
          88 => 'icon-lock',
          89 => 'icon-lock-open',
          90 => 'icon-login',
          91 => 'icon-logout',
          92 => 'icon-loop',
          93 => 'icon-magic-wand',
          94 => 'icon-magnet',
          95 => 'icon-magnifier',
          96 => 'icon-magnifier-add',
          97 => 'icon-magnifier-remove',
          98 => 'icon-map',
          99 => 'icon-microphone',
          100 => 'icon-mouse',
          101 => 'icon-moustache',
          102 => 'icon-music-tone',
          103 => 'icon-music-tone-alt',
          104 => 'icon-note',
          105 => 'icon-notebook',
          106 => 'icon-paper-clip',
          107 => 'icon-paper-plane',
          108 => 'icon-pencil',
          109 => 'icon-picture',
          110 => 'icon-pie-chart',
          111 => 'icon-pin',
          112 => 'icon-plane',
          113 => 'icon-playlist',
          114 => 'icon-plus',
          115 => 'icon-pointer',
          116 => 'icon-power',
          117 => 'icon-present',
          118 => 'icon-printer',
          119 => 'icon-puzzle',
          120 => 'icon-question',
          121 => 'icon-refresh',
          122 => 'icon-reload',
          123 => 'icon-rocket',
          124 => 'icon-screen-desktop',
          125 => 'icon-screen-smartphone',
          126 => 'icon-screen-tablet',
          127 => 'icon-settings',
          128 => 'icon-share',
          129 => 'icon-share-alt',
          130 => 'icon-shield',
          131 => 'icon-shuffle',
          132 => 'icon-size-actual',
          133 => 'icon-size-fullscreen',
          134 => 'icon-social-dribbble',
          135 => 'icon-social-dropbox',
          136 => 'icon-social-facebook',
          137 => 'icon-social-tumblr',
          138 => 'icon-social-twitter',
          139 => 'icon-social-youtube',
          140 => 'icon-speech',
          141 => 'icon-speedometer',
          142 => 'icon-star',
          143 => 'icon-support',
          144 => 'icon-symbol-female',
          145 => 'icon-symbol-male',
          146 => 'icon-tag',
          147 => 'icon-target',
          148 => 'icon-trash',
          149 => 'icon-trophy',
          150 => 'icon-umbrella',
          151 => 'icon-user',
          152 => 'icon-user-female',
          153 => 'icon-user-follow',
          154 => 'icon-user-following',
          155 => 'icon-user-unfollow',
          156 => 'icon-users',
          157 => 'icon-vector',
          158 => 'icon-volume-1',
          159 => 'icon-volume-2',
          160 => 'icon-volume-off',
          161 => 'icon-wallet',
          162 => 'icon-wrench',
        ];
    }
}
